repos:
  - repo: local
    hooks:
      - id: autopep8
        name: autopep8
        entry: autopep8
        language: system
        types: [python]
        args:
          - --in-place
          - --aggressive
          - --aggressive
        
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: true
        args:
          - --fail-under=10